version: '2.2'
services:
  mssql:
    build: ./mssql
    container_name: sql1
    restart: always
    ports:
      - 1433:1433
    networks:
      - elastic
    volumes:
      - mssql:/var/opt/mssql
  elasticsearch:
    image: elasticsearch:7.13.2
    container_name: elasticsearch
    environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    restart: always
    depends_on:
      - mssql
    ports:
      - 9200:9200
    networks:
      - elastic
  logstash:
    build: ./logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 5001:5001
    container_name: logstash
    restart: always
    networks:
      - elastic
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config:/usr/share/logstash/pipeline
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    environment:
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - elastic

volumes:
  data:
    driver: local
  mssql:
    driver: local

networks:
  elastic:
    driver: bridge